package parse

var serviceMap = `{
  "2": {
    "_id": 2,
    "typeId": 2,
    "typeDesc": "USER",
    "name": "USER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "10": {
    "_id": 10,
    "typeId": 10,
    "typeDesc": "WEBPAGE",
    "name": "WEBPAGE",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "20": {
    "_id": 20,
    "typeId": 20,
    "typeDesc": "ANDROID",
    "name": "MOBILE",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "30": {
    "_id": 30,
    "typeId": 30,
    "typeDesc": "IOS",
    "name": "MOBILE",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1010": {
    "_id": 1010,
    "typeId": 1010,
    "typeDesc": "TOMCAT",
    "name": "TOMCAT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1011": {
    "_id": 1011,
    "typeId": 1011,
    "typeDesc": "TOMCAT_METHOD",
    "name": "TOMCAT_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1013": {
    "_id": 1013,
    "typeId": 1013,
    "typeDesc": "BES",
    "name": "BES",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1014": {
    "_id": 1014,
    "typeId": 1014,
    "typeDesc": "BES_METHOD",
    "name": "BES_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1015": {
    "_id": 1015,
    "typeId": 1015,
    "typeDesc": "ESB_PROVIDER",
    "name": "ESB_PROVIDER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1016": {
    "_id": 1016,
    "typeId": 1016,
    "typeDesc": "ESB_PROVIDER_METHOD",
    "name": "ESB_PROVIDER_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1020": {
    "_id": 1020,
    "typeId": 1020,
    "typeDesc": "APUSIC",
    "name": "APUSIC",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1021": {
    "_id": 1021,
    "typeId": 1021,
    "typeDesc": "APUSIC_METHOD",
    "name": "APUSIC_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1030": {
    "_id": 1030,
    "typeId": 1030,
    "typeDesc": "JETTY",
    "name": "JETTY",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1031": {
    "_id": 1031,
    "typeId": 1031,
    "typeDesc": "JETTY_METHOD",
    "name": "JETTY_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1040": {
    "_id": 1040,
    "typeId": 1040,
    "typeDesc": "JBOSS",
    "name": "JBOSS",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1041": {
    "_id": 1041,
    "typeId": 1041,
    "typeDesc": "JBOSS_METHOD",
    "name": "JBOSS_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1050": {
    "_id": 1050,
    "typeId": 1050,
    "typeDesc": "WEBLOGIC",
    "name": "WEBLOGIC",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1051": {
    "_id": 1051,
    "typeId": 1051,
    "typeDesc": "WEBLOGIC_METHOD",
    "name": "WEBLOGIC_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1053": {
    "_id": 1053,
    "typeId": 1053,
    "typeDesc": "SERVICE_COMB",
    "name": "SERVICE_COMB",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1054": {
    "_id": 1054,
    "typeId": 1054,
    "typeDesc": "SERVICE_COMB_METHOD",
    "name": "SERVICE_COMB_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "1055": {
    "_id": 1055,
    "typeId": 1055,
    "typeDesc": "VERTX",
    "name": "VERTX",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "1056": {
    "_id": 1056,
    "typeId": 1056,
    "typeDesc": "VERTX_INTERNAL",
    "name": "VERTX_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "1057": {
    "_id": 1057,
    "typeId": 1057,
    "typeDesc": "VERTX_HTTP_SERVER",
    "name": "VERTX_HTTP_SERVER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1058": {
    "_id": 1058,
    "typeId": 1058,
    "typeDesc": "VERTX_HTTP_SERVER",
    "name": "VERTX_HTTP_SERVER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9140": {
    "_id": 9140,
    "typeId": 9140,
    "typeDesc": "VERTX_HTTP_CLIENT",
    "name": "VERTX_HTTP_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9141": {
    "_id": 9141,
    "typeId": 9141,
    "typeDesc": "VERTX_HTTP_CLIENT",
    "name": "VERTX_HTTP_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "9150": {
    "_id": 9150,
    "typeId": 9150,
    "typeDesc": "NETTY",
    "name": "NETTY",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9151": {
    "_id": 9151,
    "typeId": 9151,
    "typeDesc": "NETTY_INTERNAL",
    "name": "NETTY_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9152": {
    "_id": 9152,
    "typeId": 9152,
    "typeDesc": "NETTY_HTTP",
    "name": "NETTY_HTTP",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "1060": {
    "_id": 1060,
    "typeId": 1060,
    "typeDesc": "WEBSPHERE",
    "name": "WEBSPHERE",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1061": {
    "_id": 1061,
    "typeId": 1061,
    "typeDesc": "WEBSPHERE_METHOD",
    "name": "WEBSPHERE_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1070": {
    "_id": 1070,
    "typeId": 1070,
    "typeDesc": "ELASTICSEARCH",
    "name": "ELASTICSEARCH",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1071": {
    "_id": 1071,
    "typeId": 1071,
    "typeDesc": "ELASTICSEARCH_METHOD",
    "name": "ELASTICSEARCH_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1080": {
    "_id": 1080,
    "typeId": 1080,
    "typeDesc": "TONGWEB",
    "name": "TONGWEB",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1081": {
    "_id": 1081,
    "typeId": 1081,
    "typeDesc": "TONGWEB_METHOD",
    "name": "TONGWEB_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1100": {
    "_id": 1100,
    "typeId": 1100,
    "typeDesc": "THRIFT_SERVER",
    "name": "THRIFT_SERVER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1101": {
    "_id": 1101,
    "typeId": 1101,
    "typeDesc": "THRIFT_SERVER",
    "name": "THRIFT_SERVER_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1110": {
    "_id": 1110,
    "typeId": 1110,
    "typeDesc": "DUBBO_PROVIDER",
    "name": "DUBBO_PROVIDER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1111": {
    "_id": 1111,
    "typeId": 1111,
    "typeDesc": "HSF_PROVIDER",
    "name": "HSF_PROVIDER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1120": {
    "_id": 1120,
    "typeId": 1120,
    "typeDesc": "SITECHHSF_PROVIDER",
    "name": "SITECHHSF_PROVIDER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1170": {
    "_id": 1170,
    "typeId": 1170,
    "typeDesc": "UNDERTOW",
    "name": "UNDERTOW",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1171": {
    "_id": 1171,
    "typeId": 1171,
    "typeDesc": "UNDERTOW_METHOD",
    "name": "UNDERTOW_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1210": {
    "_id": 1210,
    "typeId": 1210,
    "typeDesc": "SPRING_BOOT",
    "name": "SPRING_BOOT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1500": {
    "_id": 1500,
    "typeId": 1500,
    "typeDesc": "PHP",
    "name": "PHP",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1600": {
    "_id": 1600,
    "typeId": 1600,
    "typeDesc": "GO",
    "name": "GO",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1610": {
    "_id": 1610,
    "typeId": 1610,
    "typeDesc": "EJB_PROVIDER",
    "name": "EJB_PROVIDER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "1700": {
    "_id": 1700,
    "typeId": 1700,
    "typeDesc": "PYTHON",
    "name": "PYTHON",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "2050": {
    "_id": 2050,
    "typeId": 2050,
    "typeDesc": "UNKNOWN_DB",
    "name": "UNKNOWN_DB",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2051": {
    "_id": 2051,
    "typeId": 2051,
    "typeDesc": "UNKNOWN_DB",
    "name": "UNKNOWN_DB_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2100": {
    "_id": 2100,
    "typeId": 2100,
    "typeDesc": "MYSQL",
    "name": "MYSQL",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2101": {
    "_id": 2101,
    "typeId": 2101,
    "typeDesc": "MYSQL",
    "name": "MYSQL_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2150": {
    "_id": 2150,
    "typeId": 2150,
    "typeDesc": "MARIADB",
    "name": "MARIADB",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2151": {
    "_id": 2151,
    "typeId": 2151,
    "typeDesc": "MARIADB",
    "name": "MARIADB_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2200": {
    "_id": 2200,
    "typeId": 2200,
    "typeDesc": "MSSQLSERVER",
    "name": "MSSQL",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2201": {
    "_id": 2201,
    "typeId": 2201,
    "typeDesc": "MSSQLSERVER",
    "name": "MSSQL_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2300": {
    "_id": 2300,
    "typeId": 2300,
    "typeDesc": "ORACLE",
    "name": "ORACLE",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2301": {
    "_id": 2301,
    "typeId": 2301,
    "typeDesc": "ORACLE",
    "name": "ORACLE_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2400": {
    "_id": 2400,
    "typeId": 2400,
    "typeDesc": "CUBRID",
    "name": "CUBRID",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2401": {
    "_id": 2401,
    "typeId": 2401,
    "typeDesc": "CUBRID",
    "name": "CUBRID_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2500": {
    "_id": 2500,
    "typeId": 2500,
    "typeDesc": "POSTGRESQL",
    "name": "POSTGRESQL",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2501": {
    "_id": 2501,
    "typeId": 2501,
    "typeDesc": "POSTGRESQL",
    "name": "POSTGRESQL_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2600": {
    "_id": 2600,
    "typeId": 2600,
    "typeDesc": "CASSANDRA",
    "name": "CASSANDRA",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2601": {
    "_id": 2601,
    "typeId": 2601,
    "typeDesc": "CASSANDRA",
    "name": "CASSANDRA_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2700": {
    "_id": 2700,
    "typeId": 2700,
    "typeDesc": "DB2",
    "name": "DB2",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2701": {
    "_id": 2701,
    "typeId": 2701,
    "typeDesc": "DB2",
    "name": "DB2_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2800": {
    "_id": 2800,
    "typeId": 2800,
    "typeDesc": "KINGBASE",
    "name": "KINGBASE",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2801": {
    "_id": 2801,
    "typeId": 2801,
    "typeDesc": "KINGBASE",
    "name": "KINGBASE_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2850": {
    "_id": 2850,
    "typeId": 2850,
    "typeDesc": "SQLSERVER",
    "name": "SQLSERVER",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2851": {
    "_id": 2851,
    "typeId": 2851,
    "typeDesc": "SQLSERVER",
    "name": "SQLSERVER_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2860": {
    "_id": 2860,
    "typeId": 2860,
    "typeDesc": "DMSQL",
    "name": "DMSQL",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2861": {
    "_id": 2861,
    "typeId": 2861,
    "typeDesc": "DMSQL",
    "name": "DMSQL_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2880": {
    "_id": 2880,
    "typeId": 2880,
    "typeDesc": "OSCAR",
    "name": "OSCAR",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "2881": {
    "_id": 2881,
    "typeId": 2881,
    "typeDesc": "OSCAR",
    "name": "OSCAR_EXECUTE_QUERY",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "3000": {
    "_id": 3000,
    "typeId": 3000,
    "typeDesc": "NET_DEV",
    "name": "GENERIC_NET_DEV",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "3001": {
    "_id": 3001,
    "typeId": 3001,
    "typeDesc": "FIREWALL",
    "name": "FIREWALL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "3002": {
    "_id": 3002,
    "typeId": 3002,
    "typeDesc": "LOAD_BALANCE",
    "name": "LOAD_BALANCE",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "3003": {
    "_id": 3003,
    "typeId": 3003,
    "typeDesc": "NET_SERVER",
    "name": "NET_SERVER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "3004": {
    "_id": 3004,
    "typeId": 3004,
    "typeDesc": "NET_CLIENT",
    "name": "NET_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "3005": {
    "_id": 3005,
    "typeId": 3005,
    "typeDesc": "ROUTER",
    "name": "ROUTER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "3006": {
    "_id": 3006,
    "typeId": 3006,
    "typeDesc": "SWITCH",
    "name": "SWITCH",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "3007": {
    "_id": 3007,
    "typeId": 3007,
    "typeDesc": "SITE",
    "name": "SITE",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5001": {
    "_id": 5001,
    "typeId": 5001,
    "typeDesc": "TCP",
    "name": "INTERNAL_TCP_METHOD",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "5010": {
    "_id": 5010,
    "typeId": 5010,
    "typeDesc": "GSON",
    "name": "GSON",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5011": {
    "_id": 5011,
    "typeId": 5011,
    "typeDesc": "JACKSON",
    "name": "JACKSON",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5012": {
    "_id": 5012,
    "typeId": 5012,
    "typeDesc": "JSON-LIB",
    "name": "JSON-LIB",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5051": {
    "_id": 5051,
    "typeId": 5051,
    "typeDesc": "SPRING",
    "name": "SPRING_MVC",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5071": {
    "_id": 5071,
    "typeId": 5071,
    "typeDesc": "SPRING_BEAN",
    "name": "SPRING_BEAN",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5500": {
    "_id": 5500,
    "typeId": 5500,
    "typeDesc": "IBATIS",
    "name": "IBATIS",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5501": {
    "_id": 5501,
    "typeId": 5501,
    "typeDesc": "IBATIS",
    "name": "IBATIS_SPRING",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5510": {
    "_id": 5510,
    "typeId": 5510,
    "typeDesc": "MYBATIS",
    "name": "MYBATIS",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "6050": {
    "_id": 6050,
    "typeId": 6050,
    "typeDesc": "DBCP",
    "name": "DBCP",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "6500": {
    "_id": 6500,
    "typeId": 6500,
    "typeDesc": "RX_JAVA",
    "name": "RX_JAVA",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "7000": {
    "_id": 7000,
    "typeId": 7000,
    "typeDesc": "MARTINI",
    "name": "MARTINI",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "7100": {
    "_id": 7100,
    "typeId": 7100,
    "typeDesc": "Flask",
    "name": "Flask",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "7500": {
    "_id": 7500,
    "typeId": 7500,
    "typeDesc": "CPP",
    "name": "CPP",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "7501": {
    "_id": 7501,
    "typeId": 7501,
    "typeDesc": "CPP_METHOD_CALL",
    "name": "CPP_METHOD_CALL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "8050": {
    "_id": 8050,
    "typeId": 8050,
    "typeDesc": "MEMCACHED",
    "name": "MEMCACHED",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "8051": {
    "_id": 8051,
    "typeId": 8051,
    "typeDesc": "MEMCACHED",
    "name": "MEMCACHED_FUTURE_GET",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "8100": {
    "_id": 8100,
    "typeId": 8100,
    "typeDesc": "ARCUS",
    "name": "ARCUS",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "8101": {
    "_id": 8101,
    "typeId": 8101,
    "typeDesc": "ARCUS",
    "name": "ARCUS_FUTURE_GET",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "8102": {
    "_id": 8102,
    "typeId": 8102,
    "typeDesc": "ARCUS-EHCACHE",
    "name": "ARCUS_EHCACHE_FUTURE_GET",
    "isQueue": false,
    "isIncludeDestinationId": 1,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "8200": {
    "_id": 8200,
    "typeId": 8200,
    "typeDesc": "REDIS",
    "name": "REDIS",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "8300": {
    "_id": 8300,
    "typeId": 8300,
    "typeDesc": "RABBITMQ_CLIENT",
    "name": "RABBITMQ_CLIENT",
    "isQueue": true,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "8301": {
    "_id": 8301,
    "typeId": 8301,
    "typeDesc": "RABBITMQ_CLIENT",
    "name": "RABBITMQ_CLIENT_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "8310": {
    "_id": 8310,
    "typeId": 8310,
    "typeDesc": "ACTIVEMQ_CLIENT",
    "name": "ACTIVEMQ_CLIENT",
    "isQueue": true,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "8311": {
    "_id": 8311,
    "typeId": 8311,
    "typeDesc": "ACTIVE_MQ_CLIENT",
    "name": "ACTIVEMQ_CLIENT_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "8400": {
    "_id": 8400,
    "typeId": 8400,
    "typeDesc": "MONGODB",
    "name": "MONGODB",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 1,
    "isUnknown": 0,
    "isUser": 0
  },
  "8410": {
    "_id": 8410,
    "typeId": 8410,
    "typeDesc": "IBMWEBSPHEREMQ_CLIENT",
    "name": "IBMWEBSPHEREMQ_CLIENT",
    "isQueue": true,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9050": {
    "_id": 9050,
    "typeId": 9050,
    "typeDesc": "HTTP_CLIENT_3",
    "name": "HTTP_CLIENT_3",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9051": {
    "_id": 9051,
    "typeId": 9051,
    "typeDesc": "HTTP_CLIENT_3",
    "name": "HTTP_CLIENT_3_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9052": {
    "_id": 9052,
    "typeId": 9052,
    "typeDesc": "HTTP_CLIENT_4",
    "name": "HTTP_CLIENT_4",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9053": {
    "_id": 9053,
    "typeId": 9053,
    "typeDesc": "HTTP_CLIENT_4",
    "name": "HTTP_CLIENT_4_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9054": {
    "_id": 9054,
    "typeId": 9054,
    "typeDesc": "GOOGLE_HTTP_CLIENT",
    "name": "GOOGLE_HTTP_CLIENT_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9055": {
    "_id": 9055,
    "typeId": 9055,
    "typeDesc": "JDK_HTTPCONNECTOR",
    "name": "JDK_HTTPURLCONNECTOR",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9056": {
    "_id": 9056,
    "typeId": 9056,
    "typeDesc": "ASYNC_HTTP_CLIENT",
    "name": "ASYNC_HTTP_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9057": {
    "_id": 9057,
    "typeId": 9057,
    "typeDesc": "ASYNC_HTTP_CLIENT",
    "name": "ASYNC_HTTP_CLIENT_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9058": {
    "_id": 9058,
    "typeId": 9058,
    "typeDesc": "OK_HTTP_CLIENT",
    "name": "OK_HTTP_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9059": {
    "_id": 9059,
    "typeId": 9059,
    "typeDesc": "OK_HTTP_CLIENT",
    "name": "OK_HTTP_CLIENT_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9060": {
    "_id": 9060,
    "typeId": 9060,
    "typeDesc": "AXIS",
    "name": "AXIS",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9061": {
    "_id": 9061,
    "typeId": 9061,
    "typeDesc": "WEBLOGIC_HTTP_PROXY",
    "name": "WEBLOGIC_HTTP_PROXY",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9080": {
    "_id": 9080,
    "typeId": 9080,
    "typeDesc": "CXF_CLIENT",
    "name": "CXF_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9100": {
    "_id": 9100,
    "typeId": 9100,
    "typeDesc": "THRIFT_CLIENT",
    "name": "THRIFT_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9101": {
    "_id": 9101,
    "typeId": 9101,
    "typeDesc": "THRIFT_CLIENT",
    "name": "THRIFT_CLIENT_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9110": {
    "_id": 9110,
    "typeId": 9110,
    "typeDesc": "DUBBO_CONSUMER",
    "name": "DUBBO_CONSUMER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9111": {
    "_id": 9111,
    "typeId": 9111,
    "typeDesc": "HSF_CONSUMER",
    "name": "HSF_CONSUMER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9120": {
    "_id": 9120,
    "typeId": 9120,
    "typeDesc": "HYSTRIX_COMMAND",
    "name": "HYSTRIX_COMMAND",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9121": {
    "_id": 9121,
    "typeId": 9121,
    "typeDesc": "HYSTRIX_COMMAND",
    "name": "HYSTRIX_COMMAND_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9130": {
    "_id": 9130,
    "typeId": 9130,
    "typeDesc": "SITECHHSF_CONSUMER",
    "name": "SITECHHSF_CONSUMER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9610": {
    "_id": 9610,
    "typeId": 9610,
    "typeDesc": "EJB_CONSUMER",
    "name": "EJB_CONSUMER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "8320": {
    "_id": 8320,
    "typeId": 8320,
    "typeDesc": "ROCKETMQ_CLIENT",
    "name": "ROCKETMQ_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "8321": {
    "_id": 8321,
    "typeId": 8321,
    "typeDesc": "ROCKETMQ_CLIENT_INTERNAL",
    "name": "ROCKETMQ_CLIENT_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "5080": {
    "_id": 5080,
    "typeId": 5080,
    "typeDesc": "HESSIAN_CLIENT",
    "name": "HESSIAN_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "5081": {
    "_id": 5081,
    "typeId": 5081,
    "typeDesc": "HESSIAN_SERVER",
    "name": "HESSIAN_SERVER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "5082": {
    "_id": 5082,
    "typeId": 5082,
    "typeDesc": "JERSEY_CLIENT",
    "name": "JERSEY_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "5083": {
    "_id": 5083,
    "typeId": 5083,
    "typeDesc": "JERSEY_SERVER",
    "name": "JERSEY_SERVER",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "8800": {
    "_id": 8800,
    "typeId": 8800,
    "typeDesc": "HBASE_CLIENT",
    "name": "HBASE_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "8801": {
    "_id": 8801,
    "typeId": 8801,
    "typeDesc": "HBASE_CLIENT_ADMIN",
    "name": "HBASE_CLIENT_ADMIN",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "8802": {
    "_id": 8802,
    "typeId": 8802,
    "typeDesc": "HBASE_CLIENT_TABLE",
    "name": "HBASE_CLIENT_TABLE",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "8803": {
    "_id": 8803,
    "typeId": 8803,
    "typeDesc": "HBASE_ASYNC_CLIENT",
    "name": "HBASE_ASYNC_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 1,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },

  "1141": {
    "_id": 1141,
    "typeId": 1141,
    "typeDesc": "REACTOR_NETTY_INTERNAL",
    "name": "REACTOR_NETTY_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "5053": {
    "_id": 5053,
    "typeId": 5053,
    "typeDesc": "WEBFLUX",
    "name": "WEBFLUX",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 1,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "6510": {
    "_id": 6510,
    "typeId": 6510,
    "typeDesc": "REACTOR",
    "name": "REACTOR",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9153": {
    "_id": 9153,
    "typeId": 9153,
    "typeDesc": "SPRING_WEBFLUX_CLIENT",
    "name": "SPRING_WEBFLUX_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9154": {
    "_id": 9154,
    "typeId": 9154,
    "typeDesc": "REACTOR_NETTY_CLIENT",
    "name": "REACTOR_NETTY_CLIENT",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "9155": {
    "_id": 9155,
    "typeId": 9155,
    "typeDesc": "REACTOR_NETTY_CLIENT_INTERNAL",
    "name": "REACTOR_NETTY_CLIENT_INTERNAL",
    "isQueue": false,
    "isIncludeDestinationId": 0,
    "isInternalMethod": 0,
    "isRecordStatistics": 0,
    "isRpcClient": 0,
    "isTerminal": 0,
    "isUnknown": 0,
    "isUser": 0
  },
  "2320": {
    "_id" : 2320,
    "typeId" : 2320,
    "typeDesc" : "OCEANBASE",
    "name" : "OCEANBASE",
    "isQueue" : false,
    "isIncludeDestinationId" : 1,
    "isInternalMethod" : 0,
    "isRecordStatistics" : 0,
    "isRpcClient" : 0,
    "isTerminal" : 1,
    "isUnknown" : 0,
    "isUser" : 0
  },
  "2321": {
    "_id" : 2321,
    "typeId" : 2321,
    "typeDesc" : "OCEANBASE",
    "name" : "OCEANBASE_EXECUTE_QUERY",
    "isQueue" : false,
    "isIncludeDestinationId" : 1,
    "isInternalMethod" : 0,
    "isRecordStatistics" : 1,
    "isRpcClient" : 0,
    "isTerminal" : 1,
    "isUnknown" : 0,
    "isUser" : 0
  },
  "6600": {
    "_id" : 6600,
    "typeId" : 6600,
    "typeDesc" : "ANT_SCHEDULER",
    "name" : "ANT_SCHEDULER",
    "isQueue" : false,
    "isIncludeDestinationId" : 0,
    "isInternalMethod" : 0,
    "isRecordStatistics" : 1,
    "isRpcClient" : 0,
    "isTerminal" : 0,
    "isUnknown" : 0,
    "isUser" : 0
  },
  "6601": {
    "_id" : 6601,
    "typeId" : 6601,
    "typeDesc" : "ANT_SCHEDULER",
    "name" : "ANT_SCHEDULER_INTERNAL",
    "isQueue" : false,
    "isIncludeDestinationId" : 0,
    "isInternalMethod" : 0,
    "isRecordStatistics" : 0,
    "isRpcClient" : 0,
    "isTerminal" : 0,
    "isUnknown" : 0,
    "isUser" : 0
  },
  "5091": {
    "_id" :5091,
    "typeId" :5091,
    "typeDesc": "SPRING_CLOUD_FEIGN",
    "name" : "SPRING_CLOUD_FEIGN",
    "isQueue":false,
    "isIncludeDestinationId":0,
    "isInternalMethod":0,
    "isRecordStatistics":0,
    "isRpcClient":1,
    "isTerminal":0,
    "isUnknown":0,
    "isUser":0
  },
  "5092":{
    "_id":5092,
    "typeId":5092,
    "typeDesc":"FEIGN_CLIENT",
    "name":"FEIGN_CLIENT",
    "isQueue":false,
    "isIncludeDestinationId":0,
    "isInternalMethod":0,
    "isRecordStatistics":1,
    "isRpcClient":1,
    "isTerminal":0,
    "isUnknown":0,
    "isUser":0
  }
}
`
